name: "Push Image To ECR"

on:
  push:
    tags:
      - "v*"

jobs:
  push-image-to-ecr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm
      - name: Install packages
        run: npm ci
